site_name: MongoDB for Drupal
nav:
  - Home: 'index.md'
  - Installation: 'install.md'
  - File system layout: 'layout.md'
  - Modules:
    - 'Driver: mongodb': 'modules/mongodb.md'
    - 'K/V and Queue: mongodb_storage': 'modules/mongodb_storage.md'
    - 'Logger: mongodb_watchdog': 'modules/mongodb_watchdog.md'
  - Development:
    - 'Bespoke code': 'bespoke.md'
    - 'Tests': 'tests.md'
repo_url: https://github.com/fgm/mongodb
markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: light green
    #scheme: default
  icon:
    logo: fontawesome/brands/drupal #material/drupal
