site_name: MongoDB for Drupal
pages:
  - Home: 'index.md'
  - Installation: 'install.md'
  - Layout: 'layout.md'
  - Modules:
    - 'Driver: mongodb': 'modules/mongodb.md'
    - 'Key-value: mongodb_storage': 'modules/mongodb_storage.md'
    - 'Logger: mongodb_watchdog': 'modules/mongodb_watchdog.md'
  - Development:
    - 'Bespoke code': 'bespoke.md'
    - 'Tests': 'tests.md'
theme: readthedocs
repo_url: https://github.com/FGM/mongodb
markdown_extensions:
  - footnotes
